<?xml version='1.0' encoding='UTF-8' standalone='yes'?>
<!-- Document definition -->
<!DOCTYPE MEME[
<!ELEMENT MEME (
  training_set,
  model, 
  motifs, 
  scanned_sites_summary?
)>
<!ATTLIST MEME 
  version CDATA #REQUIRED
  release CDATA #REQUIRED
>
<!-- Training-set elements -->
<!ELEMENT training_set (alphabet, ambigs, sequence+, letter_frequencies)>
<!ATTLIST training_set datafile CDATA #REQUIRED length CDATA #REQUIRED>
<!ELEMENT alphabet (letter+)>
<!ATTLIST alphabet id (amino-acid|nucleotide) #REQUIRED
                   length CDATA #REQUIRED>
<!ELEMENT ambigs (letter+)>
<!ELEMENT letter EMPTY>
<!ATTLIST letter id ID #REQUIRED>
<!ATTLIST letter symbol CDATA #REQUIRED>
<!ELEMENT sequence EMPTY>
<!ATTLIST sequence id ID #REQUIRED
                   name CDATA #REQUIRED
                   length CDATA #REQUIRED
                   weight CDATA #REQUIRED
>
<!ELEMENT letter_frequencies (alphabet_array)>

<!-- Model elements -->
<!ELEMENT model (
  command_line,
  host,
  type,
  nmotifs,
  evalue_threshold,
  object_function,
  min_width,
  max_width,
  minic,
  wg,
  ws,
  endgaps,
  minsites,
  maxsites,
  wnsites,
  prob,
  spmap,
  spfuzz,
  prior,
  beta,
  maxiter,
  distance,
  num_sequences,
  num_positions,
  seed,
  seqfrac,
  strands,
  priors_file,
  reason_for_stopping,
  background_frequencies
)>
<!ELEMENT command_line (#PCDATA)*>
<!ELEMENT host (#PCDATA)*>
<!ELEMENT type (#PCDATA)*>
<!ELEMENT nmotifs (#PCDATA)*>
<!ELEMENT evalue_threshold (#PCDATA)*>
<!ELEMENT object_function (#PCDATA)*>
<!ELEMENT min_width (#PCDATA)*>
<!ELEMENT max_width (#PCDATA)*>
<!ELEMENT minic (#PCDATA)*>
<!ELEMENT wg (#PCDATA)*>
<!ELEMENT ws (#PCDATA)*>
<!ELEMENT endgaps (#PCDATA)*>
<!ELEMENT minsites (#PCDATA)*>
<!ELEMENT maxsites (#PCDATA)*>
<!ELEMENT wnsites (#PCDATA)*>
<!ELEMENT prob (#PCDATA)*>
<!ELEMENT spmap (#PCDATA)*>
<!ELEMENT spfuzz (#PCDATA)*>
<!ELEMENT prior (#PCDATA)*>
<!ELEMENT beta (#PCDATA)*>
<!ELEMENT maxiter (#PCDATA)*>
<!ELEMENT distance (#PCDATA)*>
<!ELEMENT num_sequences (#PCDATA)*>
<!ELEMENT num_positions (#PCDATA)*>
<!ELEMENT seed (#PCDATA)*>
<!ELEMENT seqfrac (#PCDATA)*>
<!ELEMENT strands (#PCDATA)*>
<!ELEMENT priors_file (#PCDATA)*>
<!ELEMENT reason_for_stopping (#PCDATA)*>
<!ELEMENT background_frequencies (alphabet_array)>
<!ATTLIST background_frequencies source CDATA #REQUIRED>

<!-- Motif elements -->
<!ELEMENT motifs (motif+)>
<!ELEMENT motif (scores, probabilities, regular_expression?, contributing_sites)>
<!ATTLIST motif id ID #REQUIRED
                name CDATA #REQUIRED
                width CDATA #REQUIRED
                sites CDATA #REQUIRED
                llr CDATA #REQUIRED
                ic CDATA #REQUIRED
                re CDATA #REQUIRED
                bayes_threshold CDATA #REQUIRED
                e_value CDATA #REQUIRED
                elapsed_time CDATA #REQUIRED
>
<!ELEMENT scores (alphabet_matrix)>
<!ELEMENT probabilities (alphabet_matrix)>
<!ELEMENT regular_expression (#PCDATA)*>

<!-- Contributing site elements -->
<!-- Contributing sites are motif occurences found during the motif discovery phase -->
<!ELEMENT contributing_sites (contributing_site+)>
<!ELEMENT contributing_site (left_flank, site, right_flank)>
<!ATTLIST contributing_site sequence_id IDREF #REQUIRED
                          position CDATA #REQUIRED
                          strand (plus|minus|none) 'none'
                          pvalue CDATA #REQUIRED
>
<!-- The left_flank contains the sequence for 10 bases to the left of the motif start -->
<!ELEMENT left_flank (#PCDATA)>
<!-- The site contains the sequence for the motif instance -->
<!ELEMENT site (letter_ref+)>
<!-- The right_flank contains the sequence for 10 bases to the right of the motif end -->
<!ELEMENT right_flank (#PCDATA)>

<!-- Scanned site elements -->
<!-- Scanned sites are motif occurences found during the sequence scan phase -->
<!ELEMENT scanned_sites_summary (scanned_sites+)>
<!ATTLIST scanned_sites_summary p_thresh CDATA #REQUIRED>
<!ELEMENT scanned_sites (scanned_site*)>
<!ATTLIST scanned_sites sequence_id IDREF #REQUIRED
                        pvalue CDATA #REQUIRED
                        num_sites CDATA #REQUIRED>
<!ELEMENT scanned_site EMPTY>
<!ATTLIST scanned_site  motif_id IDREF #REQUIRED
                        strand (plus|minus|none) 'none'
                        position CDATA #REQUIRED
                        pvalue CDATA #REQUIRED>

<!-- Utility elements -->
<!-- A reference to a letter in the alphabet -->
<!ELEMENT letter_ref EMPTY>
<!ATTLIST letter_ref letter_id IDREF #REQUIRED>
<!-- A alphabet-array contains one floating point value for each letter in an alphabet -->
<!ELEMENT alphabet_array (value+)>
<!ELEMENT value (#PCDATA)>
<!ATTLIST value letter_id IDREF #REQUIRED>

<!-- A alphabet_matrix contains one alphabet_array for each position in a motif -->
<!ELEMENT alphabet_matrix (alphabet_array+)>

]>
<!-- Begin document body -->
<MEME version="4.4.0" release="Tue Apr 27 10:09:30 EST 2010">
<training_set datafile="/home/ethering/projects/scri_nblrr/sequences/reduced_id/Combined_R_genes_reduced_extraSOL_reduced.faa.fa" length="53">
<alphabet id="amino-acid" length="20">
<letter id="letter_A" symbol="A"/>
<letter id="letter_C" symbol="C"/>
<letter id="letter_D" symbol="D"/>
<letter id="letter_E" symbol="E"/>
<letter id="letter_F" symbol="F"/>
<letter id="letter_G" symbol="G"/>
<letter id="letter_H" symbol="H"/>
<letter id="letter_I" symbol="I"/>
<letter id="letter_K" symbol="K"/>
<letter id="letter_L" symbol="L"/>
<letter id="letter_M" symbol="M"/>
<letter id="letter_N" symbol="N"/>
<letter id="letter_P" symbol="P"/>
<letter id="letter_Q" symbol="Q"/>
<letter id="letter_R" symbol="R"/>
<letter id="letter_S" symbol="S"/>
<letter id="letter_T" symbol="T"/>
<letter id="letter_V" symbol="V"/>
<letter id="letter_W" symbol="W"/>
<letter id="letter_Y" symbol="Y"/>
</alphabet>
<ambigs>
<letter id="letter_B" symbol="B"/>
<letter id="letter_U" symbol="U"/>
<letter id="letter_X" symbol="X"/>
<letter id="letter_Z" symbol="Z"/>
<letter id="letter_star" symbol="*"/>
<letter id="letter_-" symbol="-"/>
</ambigs>
<sequence id="sequence_0" name="A5" length="205" weight="1.000000" />
<sequence id="sequence_1" name="BS2" length="905" weight="1.000000" />
<sequence id="sequence_2" name="Bs4" length="1146" weight="1.000000" />
<sequence id="sequence_3" name="Gpa2" length="912" weight="1.000000" />
<sequence id="sequence_4" name="Gro1-4" length="1136" weight="1.000000" />
<sequence id="sequence_5" name="Hero" length="1283" weight="1.000000" />
<sequence id="sequence_6" name="I2" length="1266" weight="1.000000" />
<sequence id="sequence_7" name="Mi1.2" length="1257" weight="1.000000" />
<sequence id="sequence_8" name="N" length="1141" weight="1.000000" />
<sequence id="sequence_9" name="NL25" length="533" weight="1.000000" />
<sequence id="sequence_10" name="NL27" length="821" weight="1.000000" />
<sequence id="sequence_11" name="NRC1" length="888" weight="1.000000" />
<sequence id="sequence_12" name="PSH-RGH6" length="873" weight="1.000000" />
<sequence id="sequence_13" name="R1" length="1293" weight="1.000000" />
<sequence id="sequence_14" name="R2" length="845" weight="1.000000" />
<sequence id="sequence_15" name="R3a" length="1282" weight="1.000000" />
<sequence id="sequence_16" name="RGA2-Ca" length="957" weight="1.000000" />
<sequence id="sequence_17" name="RGA2-Sb" length="970" weight="1.000000" />
<sequence id="sequence_18" name="RPS4" length="1217" weight="1.000000" />
<sequence id="sequence_19" name="Rbi-bt1" length="988" weight="1.000000" />
<sequence id="sequence_20" name="Rpi-blb2" length="1267" weight="1.000000" />
<sequence id="sequence_21" name="Rpi-blb3" length="847" weight="1.000000" />
<sequence id="sequence_22" name="Rpi-vnt1.3" length="905" weight="1.000000" />
<sequence id="sequence_23" name="Rx" length="937" weight="1.000000" />
<sequence id="sequence_24" name="TVR-A/B" length="1245" weight="1.000000" />
<sequence id="sequence_25" name="Tm-2" length="848" weight="1.000000" />
<sequence id="sequence_26" name="ry-1" length="1126" weight="1.000000" />
<sequence id="sequence_27" name="gi|22252946|gb|AAM94164.1|" length="921" weight="1.000000" />
<sequence id="sequence_28" name="gi|7110565|gb|AAF36987.1|AF234174_1" length="909" weight="1.000000" />
<sequence id="sequence_29" name="gi|33302327|gb|AAQ01784.1|" length="921" weight="1.000000" />
<sequence id="sequence_30" name="gi|270267805|gb|ACZ65507.1|" length="946" weight="1.000000" />
<sequence id="sequence_31" name="gi|33943720|gb|AAQ55541.1|" length="951" weight="1.000000" />
<sequence id="sequence_32" name="gi|28565622|gb|AAO43441.1|" length="961" weight="1.000000" />
<sequence id="sequence_33" name="gi|12957126|emb|CAC29242.1|" length="956" weight="1.000000" />
<sequence id="sequence_34" name="gi|86361429|gb|ABC94599.1|" length="1032" weight="1.000000" />
<sequence id="sequence_35" name="gi|114329518|gb|ABI64281.1|" length="1056" weight="1.000000" />
<sequence id="sequence_36" name="gi|37777304|dbj|BAA76282.2|" length="1251" weight="1.000000" />
<sequence id="sequence_37" name="gi|47027820|gb|AAT08955.1|" length="1279" weight="1.000000" />
<sequence id="sequence_38" name="gi|37624724|gb|AAQ96158.1|" length="1415" weight="1.000000" />
<sequence id="sequence_39" name="gi|5702196|gb|AAD47197.1|AF107293_1" length="1292" weight="1.000000" />
<sequence id="sequence_40" name="gi|15231371|ref|NP_187360.1|" length="926" weight="1.000000" />
<sequence id="sequence_41" name="gi|15231449|ref|NP_190237.1|" length="835" weight="1.000000" />
<sequence id="sequence_42" name="gi|15239876|ref|NP_199160.1|" length="908" weight="1.000000" />
<sequence id="sequence_43" name="gi|62632823|gb|AAX89382.1|" length="1229" weight="1.000000" />
<sequence id="sequence_44" name="gi|62632825|gb|AAX89383.1|" length="1249" weight="1.000000" />
<sequence id="sequence_45" name="gi|15236112|ref|NP_194339.1|" length="909" weight="1.000000" />
<sequence id="sequence_46" name="gi|15221252|ref|NP_172686.1|" length="889" weight="1.000000" />
<sequence id="sequence_47" name="gi|1842251|gb|AAB47618.1|" length="1305" weight="1.000000" />
<sequence id="sequence_48" name="gi|13517468|gb|AAK28805.1|AF310960_1" length="1196" weight="1.000000" />
<sequence id="sequence_49" name="gi|30692151|ref|NP_190034.2|" length="1194" weight="1.000000" />
<sequence id="sequence_50" name="gi|15242354|ref|NP_199338.1|" length="1217" weight="1.000000" />
<sequence id="sequence_51" name="gi|27466164|gb|AAN86124.1|" length="1055" weight="1.000000" />
<sequence id="sequence_52" name="gi|145334739|ref|NP_001078715.1|" length="1187" weight="1.000000" />
<letter_frequencies>
<alphabet_array>
<value letter_id="letter_A">0.044</value>
<value letter_id="letter_C">0.024</value>
<value letter_id="letter_D">0.058</value>
<value letter_id="letter_E">0.076</value>
<value letter_id="letter_F">0.041</value>
<value letter_id="letter_G">0.051</value>
<value letter_id="letter_H">0.026</value>
<value letter_id="letter_I">0.063</value>
<value letter_id="letter_K">0.070</value>
<value letter_id="letter_L">0.134</value>
<value letter_id="letter_M">0.023</value>
<value letter_id="letter_N">0.046</value>
<value letter_id="letter_P">0.037</value>
<value letter_id="letter_Q">0.034</value>
<value letter_id="letter_R">0.053</value>
<value letter_id="letter_S">0.080</value>
<value letter_id="letter_T">0.041</value>
<value letter_id="letter_V">0.060</value>
<value letter_id="letter_W">0.014</value>
<value letter_id="letter_Y">0.025</value>
</alphabet_array>
</letter_frequencies>
</training_set>
<model>
<command_line>meme -oc meme_psp /home/ethering/projects/scri_nblrr/sequences/reduced_id/Combined_R_genes_reduced_extraSOL_reduced.faa.fa -nmotifs 20 -psp psp.txt </command_line>
<host>jic62218</host>
<type>zoops</type>
<nmotifs>20</nmotifs>
<evalue_threshold>inf</evalue_threshold>
<object_function>E-value of product of p-values</object_function>
<min_width>4</min_width>
<max_width>50</max_width>
<minic>    0.00</minic>
<wg>11</wg>
<ws>1</ws>
<endgaps>yes</endgaps>
<minsites>2</minsites>
<maxsites>53</maxsites>
<wnsites>0.8</wnsites>
<prob>1</prob>
<spmap>pam</spmap>
<spfuzz>120</spfuzz>
<prior>megap</prior>
<beta>275410</beta>
<maxiter>50</maxiter>
<distance>1e-05</distance>
<num_sequences>53</num_sequences>
<num_positions>55082</num_positions>
<seed>0</seed>
<seqfrac>       1</seqfrac>
<strands>none</strands>
<priors_file>prior30.plib</priors_file>
<reason_for_stopping>Stopped because nmotifs = 20 reached.</reason_for_stopping>
<background_frequencies source="dataset with add-one prior applied">
<alphabet_array>
<value letter_id="letter_A">0.043846</value>
<value letter_id="letter_C">0.023992</value>
<value letter_id="letter_D">0.058310</value>
<value letter_id="letter_E">0.076023</value>
<value letter_id="letter_F">0.040706</value>
<value letter_id="letter_G">0.051142</value>
<value letter_id="letter_H">0.025698</value>
<value letter_id="letter_I">0.063065</value>
<value letter_id="letter_K">0.070124</value>
<value letter_id="letter_L">0.134296</value>
<value letter_id="letter_M">0.023103</value>
<value letter_id="letter_N">0.045643</value>
<value letter_id="letter_P">0.036677</value>
<value letter_id="letter_Q">0.034391</value>
<value letter_id="letter_R">0.053265</value>
<value letter_id="letter_S">0.079906</value>
<value letter_id="letter_T">0.040597</value>
<value letter_id="letter_V">0.060034</value>
<value letter_id="letter_W">0.013901</value>
<value letter_id="letter_Y">0.025280</value>
</alphabet_array>
</background_frequencies>
</model>
<motifs>
<motif id="motif_1" name="1" width="21" sites="52" ic="61.3" re="59.9" llr="2159" e_value="1.1e-594" bayes_threshold="11.6504" elapsed_time="265.960621">
<scores>
<alphabet_matrix>
<alphabet_array>
<value letter_id="letter_A">7</value>
<value letter_id="letter_C">-28</value>
<value letter_id="letter_D">-731</value>
<value letter_id="letter_E">-758</value>
<value letter_id="letter_F">-693</value>
<value letter_id="letter_G">247</value>
<value letter_id="letter_H">-684</value>
<value letter_id="letter_I">-710</value>
<value letter_id="letter_K">-771</value>
<value letter_id="letter_L">-763</value>
<value letter_id="letter_M">-611</value>
<value letter_id="letter_N">-605</value>
<value letter_id="letter_P">262</value>
<value letter_id="letter_Q">-616</value>
<value letter_id="letter_R">-689</value>
<value letter_id="letter_S">225</value>
<value letter_id="letter_T">-393</value>
<value letter_id="letter_V">-528</value>
<value letter_id="letter_W">43</value>
<value letter_id="letter_Y">-42</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-388</value>
<value letter_id="letter_C">-476</value>
<value letter_id="letter_D">-621</value>
<value letter_id="letter_E">-634</value>
<value letter_id="letter_F">-429</value>
<value letter_id="letter_G">-602</value>
<value letter_id="letter_H">-621</value>
<value letter_id="letter_I">355</value>
<value letter_id="letter_K">-595</value>
<value letter_id="letter_L">-109</value>
<value letter_id="letter_M">-252</value>
<value letter_id="letter_N">-563</value>
<value letter_id="letter_P">-596</value>
<value letter_id="letter_Q">-557</value>
<value letter_id="letter_R">-606</value>
<value letter_id="letter_S">-570</value>
<value letter_id="letter_T">-385</value>
<value letter_id="letter_V">153</value>
<value letter_id="letter_W">-564</value>
<value letter_id="letter_Y">-464</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-3</value>
<value letter_id="letter_C">-349</value>
<value letter_id="letter_D">-577</value>
<value letter_id="letter_E">-524</value>
<value letter_id="letter_F">-87</value>
<value letter_id="letter_G">-439</value>
<value letter_id="letter_H">106</value>
<value letter_id="letter_I">-106</value>
<value letter_id="letter_K">-488</value>
<value letter_id="letter_L">-68</value>
<value letter_id="letter_M">-206</value>
<value letter_id="letter_N">-450</value>
<value letter_id="letter_P">-452</value>
<value letter_id="letter_Q">-402</value>
<value letter_id="letter_R">-450</value>
<value letter_id="letter_S">-406</value>
<value letter_id="letter_T">-75</value>
<value letter_id="letter_V">296</value>
<value letter_id="letter_W">365</value>
<value letter_id="letter_Y">152</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-107</value>
<value letter_id="letter_C">-472</value>
<value letter_id="letter_D">-377</value>
<value letter_id="letter_E">-234</value>
<value letter_id="letter_F">-543</value>
<value letter_id="letter_G">418</value>
<value letter_id="letter_H">-429</value>
<value letter_id="letter_I">-560</value>
<value letter_id="letter_K">-443</value>
<value letter_id="letter_L">-643</value>
<value letter_id="letter_M">-467</value>
<value letter_id="letter_N">-329</value>
<value letter_id="letter_P">-451</value>
<value letter_id="letter_Q">-436</value>
<value letter_id="letter_R">-414</value>
<value letter_id="letter_S">-366</value>
<value letter_id="letter_T">-403</value>
<value letter_id="letter_V">-484</value>
<value letter_id="letter_W">-471</value>
<value letter_id="letter_Y">-460</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-442</value>
<value letter_id="letter_C">-83</value>
<value letter_id="letter_D">-667</value>
<value letter_id="letter_E">-676</value>
<value letter_id="letter_F">40</value>
<value letter_id="letter_G">-593</value>
<value letter_id="letter_H">-573</value>
<value letter_id="letter_I">-165</value>
<value letter_id="letter_K">-631</value>
<value letter_id="letter_L">-221</value>
<value letter_id="letter_M">514</value>
<value letter_id="letter_N">-604</value>
<value letter_id="letter_P">8</value>
<value letter_id="letter_Q">-545</value>
<value letter_id="letter_R">-627</value>
<value letter_id="letter_S">-592</value>
<value letter_id="letter_T">-454</value>
<value letter_id="letter_V">-171</value>
<value letter_id="letter_W">-432</value>
<value letter_id="letter_Y">-403</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">5</value>
<value letter_id="letter_C">-451</value>
<value letter_id="letter_D">-674</value>
<value letter_id="letter_E">-721</value>
<value letter_id="letter_F">-691</value>
<value letter_id="letter_G">373</value>
<value letter_id="letter_H">-658</value>
<value letter_id="letter_I">-707</value>
<value letter_id="letter_K">-726</value>
<value letter_id="letter_L">-762</value>
<value letter_id="letter_M">-605</value>
<value letter_id="letter_N">-572</value>
<value letter_id="letter_P">259</value>
<value letter_id="letter_Q">-603</value>
<value letter_id="letter_R">-657</value>
<value letter_id="letter_S">-93</value>
<value letter_id="letter_T">-395</value>
<value letter_id="letter_V">-529</value>
<value letter_id="letter_W">-688</value>
<value letter_id="letter_Y">-670</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-661</value>
<value letter_id="letter_C">-798</value>
<value letter_id="letter_D">-773</value>
<value letter_id="letter_E">-874</value>
<value letter_id="letter_F">-858</value>
<value letter_id="letter_G">428</value>
<value letter_id="letter_H">-770</value>
<value letter_id="letter_I">-949</value>
<value letter_id="letter_K">-849</value>
<value letter_id="letter_L">-957</value>
<value letter_id="letter_M">-874</value>
<value letter_id="letter_N">-753</value>
<value letter_id="letter_P">-745</value>
<value letter_id="letter_Q">-803</value>
<value letter_id="letter_R">-794</value>
<value letter_id="letter_S">-785</value>
<value letter_id="letter_T">-774</value>
<value letter_id="letter_V">-878</value>
<value letter_id="letter_W">-781</value>
<value letter_id="letter_Y">-792</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-312</value>
<value letter_id="letter_C">-413</value>
<value letter_id="letter_D">-651</value>
<value letter_id="letter_E">-599</value>
<value letter_id="letter_F">-346</value>
<value letter_id="letter_G">-515</value>
<value letter_id="letter_H">-487</value>
<value letter_id="letter_I">195</value>
<value letter_id="letter_K">-565</value>
<value letter_id="letter_L">147</value>
<value letter_id="letter_M">-6</value>
<value letter_id="letter_N">-527</value>
<value letter_id="letter_P">-523</value>
<value letter_id="letter_Q">11</value>
<value letter_id="letter_R">-526</value>
<value letter_id="letter_S">-50</value>
<value letter_id="letter_T">-329</value>
<value letter_id="letter_V">202</value>
<value letter_id="letter_W">-446</value>
<value letter_id="letter_Y">-377</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-661</value>
<value letter_id="letter_C">-798</value>
<value letter_id="letter_D">-773</value>
<value letter_id="letter_E">-874</value>
<value letter_id="letter_F">-858</value>
<value letter_id="letter_G">428</value>
<value letter_id="letter_H">-770</value>
<value letter_id="letter_I">-949</value>
<value letter_id="letter_K">-849</value>
<value letter_id="letter_L">-957</value>
<value letter_id="letter_M">-874</value>
<value letter_id="letter_N">-753</value>
<value letter_id="letter_P">-745</value>
<value letter_id="letter_Q">-803</value>
<value letter_id="letter_R">-794</value>
<value letter_id="letter_S">-785</value>
<value letter_id="letter_T">-774</value>
<value letter_id="letter_V">-878</value>
<value letter_id="letter_W">-781</value>
<value letter_id="letter_Y">-792</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-661</value>
<value letter_id="letter_C">-740</value>
<value letter_id="letter_D">-797</value>
<value letter_id="letter_E">-826</value>
<value letter_id="letter_F">-830</value>
<value letter_id="letter_G">-698</value>
<value letter_id="letter_H">-712</value>
<value letter_id="letter_I">-804</value>
<value letter_id="letter_K">382</value>
<value letter_id="letter_L">-876</value>
<value letter_id="letter_M">-765</value>
<value letter_id="letter_N">-721</value>
<value letter_id="letter_P">-709</value>
<value letter_id="letter_Q">-711</value>
<value letter_id="letter_R">-460</value>
<value letter_id="letter_S">-802</value>
<value letter_id="letter_T">-696</value>
<value letter_id="letter_V">-818</value>
<value letter_id="letter_W">-733</value>
<value letter_id="letter_Y">-750</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-342</value>
<value letter_id="letter_C">-484</value>
<value letter_id="letter_D">-618</value>
<value letter_id="letter_E">-673</value>
<value letter_id="letter_F">-616</value>
<value letter_id="letter_G">-517</value>
<value letter_id="letter_H">-579</value>
<value letter_id="letter_I">-543</value>
<value letter_id="letter_K">-598</value>
<value letter_id="letter_L">-684</value>
<value letter_id="letter_M">-475</value>
<value letter_id="letter_N">-452</value>
<value letter_id="letter_P">-556</value>
<value letter_id="letter_Q">-511</value>
<value letter_id="letter_R">-571</value>
<value letter_id="letter_S">-83</value>
<value letter_id="letter_T">452</value>
<value letter_id="letter_V">-470</value>
<value letter_id="letter_W">-619</value>
<value letter_id="letter_Y">-604</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-6</value>
<value letter_id="letter_C">-447</value>
<value letter_id="letter_D">-623</value>
<value letter_id="letter_E">-668</value>
<value letter_id="letter_F">-614</value>
<value letter_id="letter_G">-451</value>
<value letter_id="letter_H">-580</value>
<value letter_id="letter_I">-551</value>
<value letter_id="letter_K">-597</value>
<value letter_id="letter_L">-680</value>
<value letter_id="letter_M">-479</value>
<value letter_id="letter_N">-459</value>
<value letter_id="letter_P">-530</value>
<value letter_id="letter_Q">-508</value>
<value letter_id="letter_R">-151</value>
<value letter_id="letter_S">-301</value>
<value letter_id="letter_T">449</value>
<value letter_id="letter_V">-459</value>
<value letter_id="letter_W">-621</value>
<value letter_id="letter_Y">-603</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-489</value>
<value letter_id="letter_C">-554</value>
<value letter_id="letter_D">-780</value>
<value letter_id="letter_E">-722</value>
<value letter_id="letter_F">-350</value>
<value letter_id="letter_G">-702</value>
<value letter_id="letter_H">-627</value>
<value letter_id="letter_I">104</value>
<value letter_id="letter_K">-698</value>
<value letter_id="letter_L">263</value>
<value letter_id="letter_M">-221</value>
<value letter_id="letter_N">-698</value>
<value letter_id="letter_P">-622</value>
<value letter_id="letter_Q">-553</value>
<value letter_id="letter_R">-630</value>
<value letter_id="letter_S">-689</value>
<value letter_id="letter_T">-112</value>
<value letter_id="letter_V">-330</value>
<value letter_id="letter_W">-522</value>
<value letter_id="letter_Y">-494</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">421</value>
<value letter_id="letter_C">-202</value>
<value letter_id="letter_D">-453</value>
<value letter_id="letter_E">-430</value>
<value letter_id="letter_F">-380</value>
<value letter_id="letter_G">-211</value>
<value letter_id="letter_H">-417</value>
<value letter_id="letter_I">-362</value>
<value letter_id="letter_K">-429</value>
<value letter_id="letter_L">-168</value>
<value letter_id="letter_M">-64</value>
<value letter_id="letter_N">-406</value>
<value letter_id="letter_P">-460</value>
<value letter_id="letter_Q">-376</value>
<value letter_id="letter_R">-401</value>
<value letter_id="letter_S">-78</value>
<value letter_id="letter_T">-227</value>
<value letter_id="letter_V">-113</value>
<value letter_id="letter_W">-404</value>
<value letter_id="letter_Y">-390</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-5</value>
<value letter_id="letter_C">-519</value>
<value letter_id="letter_D">-349</value>
<value letter_id="letter_E">-149</value>
<value letter_id="letter_F">-490</value>
<value letter_id="letter_G">-385</value>
<value letter_id="letter_H">-295</value>
<value letter_id="letter_I">-480</value>
<value letter_id="letter_K">155</value>
<value letter_id="letter_L">-502</value>
<value letter_id="letter_M">-360</value>
<value letter_id="letter_N">-18</value>
<value letter_id="letter_P">-393</value>
<value letter_id="letter_Q">225</value>
<value letter_id="letter_R">267</value>
<value letter_id="letter_S">-166</value>
<value letter_id="letter_T">119</value>
<value letter_id="letter_V">-413</value>
<value letter_id="letter_W">-483</value>
<value letter_id="letter_Y">52</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">257</value>
<value letter_id="letter_C">-466</value>
<value letter_id="letter_D">-286</value>
<value letter_id="letter_E">-24</value>
<value letter_id="letter_F">-20</value>
<value letter_id="letter_G">-42</value>
<value letter_id="letter_H">-256</value>
<value letter_id="letter_I">-420</value>
<value letter_id="letter_K">192</value>
<value letter_id="letter_L">-127</value>
<value letter_id="letter_M">158</value>
<value letter_id="letter_N">-87</value>
<value letter_id="letter_P">-337</value>
<value letter_id="letter_Q">81</value>
<value letter_id="letter_R">-249</value>
<value letter_id="letter_S">-82</value>
<value letter_id="letter_T">-217</value>
<value letter_id="letter_V">-146</value>
<value letter_id="letter_W">-438</value>
<value letter_id="letter_Y">-39</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-478</value>
<value letter_id="letter_C">-33</value>
<value letter_id="letter_D">-852</value>
<value letter_id="letter_E">-832</value>
<value letter_id="letter_F">-490</value>
<value letter_id="letter_G">-763</value>
<value letter_id="letter_H">-798</value>
<value letter_id="letter_I">163</value>
<value letter_id="letter_K">-818</value>
<value letter_id="letter_L">108</value>
<value letter_id="letter_M">-19</value>
<value letter_id="letter_N">-770</value>
<value letter_id="letter_P">-740</value>
<value letter_id="letter_Q">-735</value>
<value letter_id="letter_R">-807</value>
<value letter_id="letter_S">-764</value>
<value letter_id="letter_T">-495</value>
<value letter_id="letter_V">298</value>
<value letter_id="letter_W">-690</value>
<value letter_id="letter_Y">-612</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-661</value>
<value letter_id="letter_C">-653</value>
<value letter_id="letter_D">-790</value>
<value letter_id="letter_E">-815</value>
<value letter_id="letter_F">291</value>
<value letter_id="letter_G">-722</value>
<value letter_id="letter_H">-404</value>
<value letter_id="letter_I">-645</value>
<value letter_id="letter_K">-756</value>
<value letter_id="letter_L">-628</value>
<value letter_id="letter_M">-564</value>
<value letter_id="letter_N">-27</value>
<value letter_id="letter_P">-712</value>
<value letter_id="letter_Q">-606</value>
<value letter_id="letter_R">-672</value>
<value letter_id="letter_S">-704</value>
<value letter_id="letter_T">-645</value>
<value letter_id="letter_V">-627</value>
<value letter_id="letter_W">-318</value>
<value letter_id="letter_Y">467</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-69</value>
<value letter_id="letter_C">-490</value>
<value letter_id="letter_D">173</value>
<value letter_id="letter_E">36</value>
<value letter_id="letter_F">-450</value>
<value letter_id="letter_G">-338</value>
<value letter_id="letter_H">56</value>
<value letter_id="letter_I">-455</value>
<value letter_id="letter_K">21</value>
<value letter_id="letter_L">-480</value>
<value letter_id="letter_M">-335</value>
<value letter_id="letter_N">299</value>
<value letter_id="letter_P">-355</value>
<value letter_id="letter_Q">-39</value>
<value letter_id="letter_R">-34</value>
<value letter_id="letter_S">-3</value>
<value letter_id="letter_T">-71</value>
<value letter_id="letter_V">-385</value>
<value letter_id="letter_W">-462</value>
<value letter_id="letter_Y">-344</value>
</alphabet_array>
<alphabet_array>
<value letter_id="letter_A">-192</value>
<value letter_id="letter_C">-474</value>